-- MySQL Script generated by MySQL Workbench
-- Sun Aug 26 17:44:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gizah
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gizah
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gizah` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
USE `gizah` ;

-- -----------------------------------------------------
-- Table `gizah`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gizah`.`aluno` (
  `matricula` CHAR(13) NOT NULL,
  `email` VARCHAR(55) NULL,
  `nome` VARCHAR(100) NOT NULL,
  `horas_computadas` SMALLINT UNSIGNED NOT NULL,
  `telefone` VARCHAR(11) NULL,
  PRIMARY KEY (`matricula`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gizah`.`relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gizah`.`relatorio` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` ENUM('Aprovado', 'Aprovado com edições', 'Rejeitado') NOT NULL,
  `aluno_matricula` CHAR(13) NOT NULL,
  PRIMARY KEY (`id`, `aluno_matricula`),
  INDEX `fk_relatorio_aluno1_idx` (`aluno_matricula` ASC),
  CONSTRAINT `fk_relatorio_aluno1`
    FOREIGN KEY (`aluno_matricula`)
    REFERENCES `gizah`.`aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gizah`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gizah`.`atividade` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NOT NULL,
  `data` DATE NOT NULL,
  `comprovante` BLOB NOT NULL,
  `horas_informadas` SMALLINT UNSIGNED NOT NULL,
  `horas_validadas` SMALLINT UNSIGNED NOT NULL,
  `relatorio_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `relatorio_id`),
  INDEX `fk_atividade_relatorio_idx` (`relatorio_id` ASC),
  CONSTRAINT `fk_atividade_relatorio`
    FOREIGN KEY (`relatorio_id`)
    REFERENCES `gizah`.`relatorio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
